export const ADD_COMPANY = 'ADD_COMPANY';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';

export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_PRICE_START = 'UPDATE_PRICE_START';
export const UPDATE_PRICE_ERROR = 'UPDATE_PRICE_ERROR';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
